import { FingerprintCatalogFamily } from './types';

export const LINUX_FREETYPE_FONTS: string[] = [
  'DejaVu Sans',
  'DejaVu Serif',
  'DejaVu Sans Mono',
  'Liberation Sans',
  'Liberation Serif',
  'Liberation Mono',
  'Ubuntu',
  'Ubuntu Medium',
  'Ubuntu Mono',
  'Noto Sans',
  'Noto Serif',
  'Noto Color Emoji',
  'FreeSans',
  'FreeSerif',
  'FreeMono',
];

/**
 * Linux desktop audio stack: PulseAudio/PipeWire on HDA-class Intel hardware.
 * Standard 48kHz duplex with a unified compressor parameter block.
 */
function linuxAudio() {
  return {
    sampleRate: 48000 as const,
    channelCount: 2 as const,
    oscillatorLatencyMs: 9,
    noiseOffset: 0.00012,
    dynamicsCompressorParams: {
      threshold: -24,
      knee: 30,
      ratio: 12,
      attack: 0.003,
      release: 0.25,
    },
  };
}

/**
 * 6 Curated Linux Desktop Families with documented citations (StatCounter Linux Desktop share 2026).
 * Total weight sums to 0.18 (Linux desktop pool of the normalized catalog).
 */
export const LINUX_FINGERPRINT_CATALOG: FingerprintCatalogFamily[] = [
  {
    id: 'linux-ubuntu-2404-intel-uhd-gnome',
    displayName: 'Ubuntu 24.04 LTS GNOME / Intel UHD Graphics 770 (Mesa)',
    weight: 0.05,
    os: 'linux',
    gpu: {
      vendor: 'Google Inc. (Intel)',
      renderer: 'Mesa Intel(R) UHD Graphics 770 (ADL-S GT1)',
      webgpuAdapter: 'Intel(R) UHD Graphics 770 (Mesa)',
      limitsClass: 'integrated',
    },
    cpu: { coresMin: 8, coresMax: 16, arch: 'x86_64' },
    ramGB: [8, 16],
    screen: {
      resolutions: [{ width: 1920, height: 1080 }, { width: 2560, height: 1440 }],
      dpr: 1.25,
      colorDepth: 24,
    },
    screenProfile: {
      width: 1920,
      height: 1080,
      availWidth: 1920,
      availHeight: 1052,
      colorDepth: 24,
      pixelDepth: 24,
      scaleFactor: 1.25,
      isRetina: false,
    },
    scaleFactor: 1.25,
    audioSignature: linuxAudio(),
    fontInventory: [...LINUX_FREETYPE_FONTS],
    platformVersionRange: ['24.04', '24.04.1'],
    fontsClass: 'linux-freetype',
    localePool: ['en-US', 'en-GB', 'de-DE', 'fr-FR', 'es-ES'],
    coherenceConstraints: {
      mobile: false,
      platform: 'linux',
      platformArch: 'x86',
      bitness: '64',
    },
    uaProfile: {
      userAgent:
        'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36',
      platformVersion: '24.04.0',
      architecture: 'x86',
      bitness: '64',
      brands: [
        { brand: 'Chromium', version: '131' },
        { brand: 'Not;A=Brand', version: '24' },
        { brand: 'Google Chrome', version: '131' },
      ],
    },
    gpuRenderer: 'Mesa Intel(R) UHD Graphics 770 (ADL-S GT1)',
    citation: {
      source: 'StatCounter Global Stats - Linux Desktop Distro Market Share',
      date: '2026-02',
      notes: 'Ubuntu 24.04 LTS GNOME with Mesa Intel UHD graphics stack, primary enterprise Linux workstation.',
    },
  },
  {
    id: 'linux-ubuntu-2204-amd-radeon-gnome',
    displayName: 'Ubuntu 22.04 LTS / AMD Radeon RX 6700 XT (radeonsi)',
    weight: 0.04,
    os: 'linux',
    gpu: {
      vendor: 'Google Inc. (AMD)',
      renderer: 'ANGLE (AMD, AMD Radeon RX 6700 XT (radeonsi navi22 LLVM 15.0.7), OpenGL 4.6)',
      webgpuAdapter: 'AMD Radeon RX 6700 XT (radv)',
      limitsClass: 'mid-range',
    },
    cpu: { coresMin: 6, coresMax: 12, arch: 'x86_64' },
    ramGB: [16, 32],
    screen: {
      resolutions: [{ width: 1920, height: 1080 }, { width: 2560, height: 1440 }],
      dpr: 1,
      colorDepth: 24,
    },
    screenProfile: {
      width: 1920,
      height: 1080,
      availWidth: 1920,
      availHeight: 1052,
      colorDepth: 24,
      pixelDepth: 24,
      scaleFactor: 1,
      isRetina: false,
    },
    scaleFactor: 1,
    audioSignature: linuxAudio(),
    fontInventory: [...LINUX_FREETYPE_FONTS],
    platformVersionRange: ['22.04', '22.04.4'],
    fontsClass: 'linux-freetype',
    localePool: ['en-US', 'de-DE', 'ru-RU', 'zh-CN', 'ja-JP'],
    coherenceConstraints: {
      mobile: false,
      platform: 'linux',
      platformArch: 'x86',
      bitness: '64',
    },
    uaProfile: {
      userAgent:
        'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36',
      platformVersion: '22.04.0',
      architecture: 'x86',
      bitness: '64',
      brands: [
        { brand: 'Chromium', version: '130' },
        { brand: 'Not;A=Brand', version: '24' },
        { brand: 'Google Chrome', version: '130' },
      ],
    },
    gpuRenderer: 'AMD Radeon RX 6700 XT (radeonsi, navi22, LLVM 15.0.7, DRM 3.42)',
    citation: {
      source: 'StatCounter Global Stats - Linux Desktop Distro Market Share',
      date: '2026-01',
      notes: 'Ubuntu 22.04 LTS GNOME on AMD Radeon 6000 series with open-source Mesa radeonsi driver.',
    },
  },
  {
    id: 'linux-fedora-40-intel-arc-gnome',
    displayName: 'Fedora 40 Workstation / Intel Arc A770 (Mesa DG2)',
    weight: 0.035,
    os: 'linux',
    gpu: {
      vendor: 'Google Inc. (Intel)',
      renderer: 'Mesa Intel(R) Arc(tm) A770 Graphics (DG2)',
      webgpuAdapter: 'Intel(R) Arc(tm) A770 Graphics (DG2)',
      limitsClass: 'mid-range',
    },
    cpu: { coresMin: 8, coresMax: 20, arch: 'x86_64' },
    ramGB: [16, 32],
    screen: {
      resolutions: [{ width: 1920, height: 1080 }, { width: 3840, height: 2160 }],
      dpr: 1,
      colorDepth: 24,
    },
    screenProfile: {
      width: 3840,
      height: 2160,
      availWidth: 3840,
      availHeight: 2132,
      colorDepth: 24,
      pixelDepth: 24,
      scaleFactor: 1,
      isRetina: false,
    },
    scaleFactor: 1,
    audioSignature: linuxAudio(),
    fontInventory: [...LINUX_FREETYPE_FONTS],
    platformVersionRange: ['40', '40.1'],
    fontsClass: 'linux-freetype',
    localePool: ['en-US', 'en-CA', 'de-DE', 'pl-PL', 'nl-NL'],
    coherenceConstraints: {
      mobile: false,
      platform: 'linux',
      platformArch: 'x86',
      bitness: '64',
    },
    uaProfile: {
      userAgent:
        'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36',
      platformVersion: '40.0',
      architecture: 'x86',
      bitness: '64',
      brands: [
        { brand: 'Chromium', version: '131' },
        { brand: 'Not;A=Brand', version: '24' },
        { brand: 'Google Chrome', version: '131' },
      ],
    },
    gpuRenderer: 'Mesa Intel(R) Arc(tm) A770 Graphics (DG2)',
    citation: {
      source: 'StatCounter Global Stats - Linux Desktop Distro Market Share',
      date: '2026-02',
      notes: 'Fedora 40 Workstation GNOME with modern Intel Arc graphics running latest Mesa driver stack.',
    },
  },
  {
    id: 'linux-debian-12-kde-amd',
    displayName: 'Debian 12 (Bookworm) KDE / AMD Ryzen Radeon Graphics',
    weight: 0.025,
    os: 'linux',
    gpu: {
      vendor: 'Google Inc. (AMD)',
      renderer: 'ANGLE (AMD, AMD Radeon 780M Graphics (radeonsi phoenix LLVM 15.0.7), OpenGL 4.6)',
      webgpuAdapter: 'AMD Radeon 780M (radv)',
      limitsClass: 'integrated',
    },
    cpu: { coresMin: 8, coresMax: 16, arch: 'x86_64' },
    ramGB: [16, 32],
    screen: {
      resolutions: [{ width: 1920, height: 1080 }, { width: 2560, height: 1440 }],
      dpr: 1,
      colorDepth: 24,
    },
    screenProfile: {
      width: 2560,
      height: 1440,
      availWidth: 2560,
      availHeight: 1412,
      colorDepth: 24,
      pixelDepth: 24,
      scaleFactor: 1,
      isRetina: false,
    },
    scaleFactor: 1,
    audioSignature: linuxAudio(),
    fontInventory: [...LINUX_FREETYPE_FONTS],
    platformVersionRange: ['12', '12.4'],
    fontsClass: 'linux-freetype',
    localePool: ['en-US', 'en-GB', 'fr-FR', 'de-DE', 'ru-RU'],
    coherenceConstraints: {
      mobile: false,
      platform: 'linux',
      platformArch: 'x86',
      bitness: '64',
    },
    uaProfile: {
      userAgent:
        'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36',
      platformVersion: '12.4.0',
      architecture: 'x86',
      bitness: '64',
      brands: [
        { brand: 'Chromium', version: '129' },
        { brand: 'Not;A=Brand', version: '24' },
        { brand: 'Google Chrome', version: '129' },
      ],
    },
    gpuRenderer: 'AMD Radeon 780M Graphics (radeonsi, phoenix, LLVM 15.0.7, DRM 3.54)',
    citation: {
      source: 'StatCounter Global Stats - Linux Desktop Distro Market Share',
      date: '2026-01',
      notes: 'Debian 12 KDE Plasma on AMD Ryzen APU with Radeon 780M integrated graphics (radeonsi).',
    },
  },
  {
    id: 'linux-ubuntu-wayland-nvidia-rtx',
    displayName: 'Ubuntu 24.04 Wayland / NVIDIA GeForce RTX 4060 (nvidia-drm)',
    weight: 0.015,
    os: 'linux',
    gpu: {
      vendor: 'Google Inc. (NVIDIA)',
      renderer: 'ANGLE (NVIDIA, NVIDIA GeForce RTX 4060 (nvidia-drm), OpenGL 4.6)',
      webgpuAdapter: 'NVIDIA GeForce RTX 4060',
      limitsClass: 'high-end',
    },
    cpu: { coresMin: 8, coresMax: 24, arch: 'x86_64' },
    ramGB: [32],
    screen: {
      resolutions: [{ width: 2560, height: 1440 }, { width: 3840, height: 2160 }],
      dpr: 1,
      colorDepth: 24,
    },
    screenProfile: {
      width: 2560,
      height: 1440,
      availWidth: 2560,
      availHeight: 1412,
      colorDepth: 24,
      pixelDepth: 24,
      scaleFactor: 1,
      isRetina: false,
    },
    scaleFactor: 1,
    audioSignature: linuxAudio(),
    fontInventory: [...LINUX_FREETYPE_FONTS],
    platformVersionRange: ['24.04', '24.04.1'],
    fontsClass: 'linux-freetype',
    localePool: ['en-US', 'en-GB', 'de-DE', 'ja-JP', 'ko-KR'],
    coherenceConstraints: {
      mobile: false,
      platform: 'linux',
      platformArch: 'x86',
      bitness: '64',
    },
    uaProfile: {
      userAgent:
        'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36',
      platformVersion: '24.04.0',
      architecture: 'x86',
      bitness: '64',
      brands: [
        { brand: 'Chromium', version: '131' },
        { brand: 'Not;A=Brand', version: '24' },
        { brand: 'Google Chrome', version: '131' },
      ],
    },
    gpuRenderer: 'NVIDIA GeForce RTX 4060/PCIe/SSE2',
    citation: {
      source: 'StatCounter Global Stats - Linux Desktop Distro Market Share / Steam Hardware Survey',
      date: '2026-02',
      notes: 'Ubuntu Wayland session with NVIDIA discrete RTX 40-series GPU on proprietary nvidia-drm driver.',
    },
  },
  {
    id: 'linux-mint-21-cinnamon-intel',
    displayName: 'Linux Mint 21.3 Cinnamon / Intel UHD Graphics 620',
    weight: 0.015,
    os: 'linux',
    gpu: {
      vendor: 'Google Inc. (Intel)',
      renderer: 'Mesa Intel(R) UHD Graphics 620 (KBL GT2)',
      webgpuAdapter: 'Intel(R) UHD Graphics 620 (Mesa)',
      limitsClass: 'integrated',
    },
    cpu: { coresMin: 4, coresMax: 8, arch: 'x86_64' },
    ramGB: [8, 16],
    screen: {
      resolutions: [{ width: 1600, height: 900 }, { width: 1920, height: 1080 }],
      dpr: 1,
      colorDepth: 24,
    },
    screenProfile: {
      width: 1920,
      height: 1080,
      availWidth: 1920,
      availHeight: 1052,
      colorDepth: 24,
      pixelDepth: 24,
      scaleFactor: 1,
      isRetina: false,
    },
    scaleFactor: 1,
    audioSignature: linuxAudio(),
    fontInventory: [...LINUX_FREETYPE_FONTS],
    platformVersionRange: ['21.3', '21.2'],
    fontsClass: 'linux-freetype',
    localePool: ['en-US', 'es-ES', 'pt-BR', 'it-IT', 'de-DE'],
    coherenceConstraints: {
      mobile: false,
      platform: 'linux',
      platformArch: 'x86',
      bitness: '64',
    },
    uaProfile: {
      userAgent:
        'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36',
      platformVersion: '21.3.0',
      architecture: 'x86',
      bitness: '64',
      brands: [
        { brand: 'Chromium', version: '128' },
        { brand: 'Not;A=Brand', version: '24' },
        { brand: 'Google Chrome', version: '128' },
      ],
    },
    gpuRenderer: 'Mesa Intel(R) UHD Graphics 620 (KBL GT2)',
    citation: {
      source: 'StatCounter Global Stats - Linux Desktop Distro Market Share',
      date: '2026-01',
      notes: 'Linux Mint 21.3 Cinnamon on legacy Intel KBL integrated graphics, popular budget desktop distribution.',
    },
  },
];

/** Alias used by UI and tests: the curated Linux desktop family set. */
export const LINUX_DESKTOP_FAMILIES = LINUX_FINGERPRINT_CATALOG;