import type { FingerprintCatalogFamily, MacHostTellPolicy } from './types';
import {
  WIN_MODERN_FONTS,
  WIN_ARM_FONTS,
  MAC_MODERN_FONTS,
  MAC_INTEL_FONTS,
  AUDIO_SIGNATURE_WIN,
  AUDIO_SIGNATURE_MAC,
} from './migration';

/**
 * Enumerated macOS-on-Windows-host tells and masking/exclusion policy.
 * Each tell describes the host discrepancy, strategy, and documented rationale.
 */
export const MACOS_HOST_TELLS_POLICY: MacHostTellPolicy[] = [
  {
    tell: 'navigator.platform',
    strategy: 'mask',
    rationale: 'Windows host reports "Win32"; macOS must report "MacIntel" per Chromium standard even on Apple Silicon ARM chips.',
  },
  {
    tell: 'navigator.userAgentData.platform',
    strategy: 'mask',
    rationale: 'UA-CH on Windows reports "Windows"; macOS requires "macOS" with architecture "arm" or "x86".',
  },
  {
    tell: 'navigator.oscpu',
    strategy: 'mask',
    rationale: 'Gecko/WebKit legacy property undefined in Chrome, but when probed must not expose Windows NT.',
  },
  {
    tell: 'navigator.maxTouchPoints',
    strategy: 'mask',
    rationale: 'macOS laptops and desktops do not have touchscreen panels; must always report 0 (Windows often reports >0 on touch/convertibles).',
  },
  {
    tell: 'WebGL unmasked renderer / ANGLE string',
    strategy: 'mask',
    rationale: 'Windows ANGLE reports "Direct3D11" or "Direct3D12"; macOS WebGL reports "Apple M1", "Apple M2", "Apple M3", "Apple M4", or "Intel Iris Plus Graphics OpenGL Engine / Metal". Direct3D strings are fatal tell.',
  },
  {
    tell: 'Screen Retina scale factor and devicePixelRatio',
    strategy: 'mask',
    rationale: 'MacBook displays are Retina with devicePixelRatio = 2.0 (or scaled 2.0+). Standard Windows 1080p is 1.0. DPR mismatch with screen resolution is a major bot-detection signal.',
  },
  {
    tell: 'Menu bar geometry (window.screen.availHeight)',
    strategy: 'mask',
    rationale: 'Windows taskbar is typically 40-48px at screen bottom; macOS menu bar is 25px (or notch-aware ~32-38px) at screen top with Dock auto-hidden or bottom-offset.',
  },
  {
    tell: 'Core audio latency and default sample rate',
    strategy: 'mask',
    rationale: 'macOS CoreAudio defaults to 44100 Hz or 48000 Hz with lower oscillator buffer latency (~8ms) compared to Windows WASAPI defaults (~10-15ms).',
  },
  {
    tell: 'System font availability',
    strategy: 'mask',
    rationale: 'Windows host lacks SF Pro / Helvetica Neue / Menlo, while possessing Segoe UI / Calibri. Font measurement probes reveal host OS fonts if not shinned/masked.',
  },
  {
    tell: 'Keyboard modifier key events (metaKey vs ctrlKey)',
    strategy: 'exclude',
    rationale: 'Physical keyboard layout differs (Command vs Control). In background headless/agent automation, keystroke mapping is synthesized via CDP Input domain; native OS shortcuts cannot be safely cross-virtualized without guest VM.',
  },
  {
    tell: 'Missing macOS-only APIs (e.g. apple-specific media decoders/codecs)',
    strategy: 'exclude',
    rationale: 'HEVC/ProRes hardware decoders in macOS AVFoundation cannot be safely synthesized on Windows DirectX host without software transcoding bugs; exclude media-codec fingerprint tests from relying on native Apple silicon decoder paths.',
  },
];

/**
 * Curated macOS M1/M2/M3/M4 + Intel families.
 * Sourced from Apple Developer hardware specifications, EveryMac public technical specs, and Chrome platform releases.
 * NO harvested personal or live-scraped telemetry.
 */
export const MACOS_FINGERPRINT_CATALOG: FingerprintCatalogFamily[] = [
  // 1. Apple Silicon M1 - MacBook Air 13" (Late 2020)
  {
    id: 'mac-m1-mba-2020',
    displayName: 'MacBook Air 13" (M1, 2020) / Apple M1 8-Core GPU',
    weight: 0.18,
    os: 'macos',
    chip: 'M1',
    gpu: {
      vendor: 'Apple Inc. (Apple)',
      renderer: 'ANGLE (Apple, Apple M1, OpenGL 4.1 Metal - 88.1)',
      webgpuAdapter: 'Apple M1',
      limitsClass: 'integrated',
    },
    gpuRenderer: 'ANGLE (Apple, Apple M1, OpenGL 4.1 Metal - 88.1)',
    cpu: { coresMin: 8, coresMax: 8, arch: 'arm64' },
    ramGB: [8, 16],
    screen: {
      resolutions: [{ width: 1440, height: 900 }, { width: 1680, height: 1050 }, { width: 1280, height: 800 }],
      dpr: 2.0,
      colorDepth: 24,
    },
    screenProfile: {
      width: 1440,
      height: 900,
      availWidth: 1440,
      availHeight: 875,
      colorDepth: 24,
      pixelDepth: 24,
      scaleFactor: 2.0,
      isRetina: true,
    },
    scaleFactor: 2.0,
    audioSignature: {
      sampleRate: 44100,
      channelCount: 2,
      oscillatorLatencyMs: 8,
      noiseOffset: 0.00008,
      dynamicsCompressorParams: {
        threshold: -24,
        knee: 30,
        ratio: 12,
        attack: 0.003,
        release: 0.25,
      },
    },
    fontInventory: [...MAC_MODERN_FONTS],
    platformVersionRange: ['13.6.7', '14.5', '14.6.1', '15.0'],
    fontsClass: 'macos-modern',
    localePool: ['en-US', 'en-GB', 'fr-FR', 'de-DE', 'es-ES', 'ja-JP'],
    coherenceConstraints: {
      mobile: false,
      platform: 'macos',
      platformArch: 'arm',
      bitness: '64',
      metalSupport: true,
    },
    uaProfile: {
      userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36',
      platformVersion: '14.5.0',
      architecture: 'arm',
      bitness: '64',
      brands: [
        { brand: 'Chromium', version: '128' },
        { brand: 'Not;A=Brand', version: '24' },
        { brand: 'Google Chrome', version: '128' },
      ],
    },
    citation: {
      source: 'Apple Developer Hardware Documentation (MacBookAir10,1)',
      date: '2026-08',
      notes: 'Standard 8-core CPU (4 performance + 4 efficiency), 7/8-core GPU, Apple Silicon M1 entry consumer laptop',
    },
    hostTellsPolicy: MACOS_HOST_TELLS_POLICY,
  },

  // 2. Apple Silicon M1 Pro - MacBook Pro 14" (2021)
  {
    id: 'mac-m1pro-mbp-14-2021',
    displayName: 'MacBook Pro 14" (M1 Pro, 2021) / Apple M1 Pro 14-Core GPU',
    weight: 0.12,
    os: 'macos',
    chip: 'M1',
    gpu: {
      vendor: 'Apple Inc. (Apple)',
      renderer: 'ANGLE (Apple, Apple M1 Pro, OpenGL 4.1 Metal - 88.1)',
      webgpuAdapter: 'Apple M1 Pro',
      limitsClass: 'mid-range',
    },
    gpuRenderer: 'ANGLE (Apple, Apple M1 Pro, OpenGL 4.1 Metal - 88.1)',
    cpu: { coresMin: 8, coresMax: 8, arch: 'arm64' },
    ramGB: [16, 32],
    screen: {
      resolutions: [{ width: 1512, height: 982 }, { width: 1800, height: 1169 }],
      dpr: 2.0,
      colorDepth: 30,
    },
    screenProfile: {
      width: 1512,
      height: 982,
      availWidth: 1512,
      availHeight: 944,
      colorDepth: 30,
      pixelDepth: 30,
      scaleFactor: 2.0,
      isRetina: true,
    },
    scaleFactor: 2.0,
    audioSignature: {
      sampleRate: 48000,
      channelCount: 2,
      oscillatorLatencyMs: 7,
      noiseOffset: 0.00007,
      dynamicsCompressorParams: {
        threshold: -24,
        knee: 30,
        ratio: 12,
        attack: 0.003,
        release: 0.25,
      },
    },
    fontInventory: [...MAC_MODERN_FONTS],
    platformVersionRange: ['13.6.7', '14.5', '14.6.1', '15.1'],
    fontsClass: 'macos-modern',
    localePool: ['en-US', 'en-CA', 'de-DE', 'en-GB', 'ja-JP', 'zh-CN'],
    coherenceConstraints: {
      mobile: false,
      platform: 'macos',
      platformArch: 'arm',
      bitness: '64',
      metalSupport: true,
    },
    uaProfile: {
      userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36',
      platformVersion: '14.6.1',
      architecture: 'arm',
      bitness: '64',
      brands: [
        { brand: 'Chromium', version: '128' },
        { brand: 'Not;A=Brand', version: '24' },
        { brand: 'Google Chrome', version: '128' },
      ],
    },
    citation: {
      source: 'Apple Developer Hardware Documentation (MacBookPro18,3)',
      date: '2026-08',
      notes: 'Liquid Retina XDR ProMotion display, Apple Silicon M1 Pro professional laptop',
    },
    hostTellsPolicy: MACOS_HOST_TELLS_POLICY,
  },

  // 3. Apple Silicon M2 - MacBook Air 13" (2022) / 15" (2023)
  {
    id: 'mac-m2-mba-2022',
    displayName: 'MacBook Air 13"/15" (M2, 2022-2023) / Apple M2 8/10-Core GPU',
    weight: 0.22,
    os: 'macos',
    chip: 'M2',
    gpu: {
      vendor: 'Apple Inc. (Apple)',
      renderer: 'ANGLE (Apple, Apple M2, OpenGL 4.1 Metal - 88.1)',
      webgpuAdapter: 'Apple M2',
      limitsClass: 'integrated',
    },
    gpuRenderer: 'ANGLE (Apple, Apple M2, OpenGL 4.1 Metal - 88.1)',
    cpu: { coresMin: 8, coresMax: 8, arch: 'arm64' },
    ramGB: [8, 16, 24],
    screen: {
      resolutions: [{ width: 1470, height: 956 }, { width: 1710, height: 1107 }],
      dpr: 2.0,
      colorDepth: 24,
    },
    screenProfile: {
      width: 1470,
      height: 956,
      availWidth: 1470,
      availHeight: 924,
      colorDepth: 24,
      pixelDepth: 24,
      scaleFactor: 2.0,
      isRetina: true,
    },
    scaleFactor: 2.0,
    audioSignature: {
      sampleRate: 44100,
      channelCount: 2,
      oscillatorLatencyMs: 8,
      noiseOffset: 0.00008,
      dynamicsCompressorParams: {
        threshold: -24,
        knee: 30,
        ratio: 12,
        attack: 0.003,
        release: 0.25,
      },
    },
    fontInventory: [...MAC_MODERN_FONTS],
    platformVersionRange: ['14.4.1', '14.5', '14.6.1', '15.0', '15.2'],
    fontsClass: 'macos-modern',
    localePool: ['en-US', 'en-GB', 'de-DE', 'fr-FR', 'it-IT', 'ja-JP', 'pt-BR'],
    coherenceConstraints: {
      mobile: false,
      platform: 'macos',
      platformArch: 'arm',
      bitness: '64',
      metalSupport: true,
    },
    uaProfile: {
      userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36',
      platformVersion: '14.6.1',
      architecture: 'arm',
      bitness: '64',
      brands: [
        { brand: 'Chromium', version: '128' },
        { brand: 'Not;A=Brand', version: '24' },
        { brand: 'Google Chrome', version: '128' },
      ],
    },
    citation: {
      source: 'Apple Developer Hardware Documentation (Mac14,2 / Mac14,15)',
      date: '2026-08',
      notes: 'Liquid Retina display with camera notch, Apple M2 second-generation Apple Silicon',
    },
    hostTellsPolicy: MACOS_HOST_TELLS_POLICY,
  },

  // 4. Apple Silicon M3 - MacBook Pro 14" (Late 2023)
  {
    id: 'mac-m3-mbp-14-2023',
    displayName: 'MacBook Pro 14" (M3, 2023) / Apple M3 10-Core GPU',
    weight: 0.16,
    os: 'macos',
    chip: 'M3',
    gpu: {
      vendor: 'Apple Inc. (Apple)',
      renderer: 'ANGLE (Apple, Apple M3, OpenGL 4.1 Metal - 89.2)',
      webgpuAdapter: 'Apple M3',
      limitsClass: 'mid-range',
    },
    gpuRenderer: 'ANGLE (Apple, Apple M3, OpenGL 4.1 Metal - 89.2)',
    cpu: { coresMin: 8, coresMax: 8, arch: 'arm64' },
    ramGB: [8, 16, 24],
    screen: {
      resolutions: [{ width: 1512, height: 982 }, { width: 1800, height: 1169 }],
      dpr: 2.0,
      colorDepth: 30,
    },
    screenProfile: {
      width: 1512,
      height: 982,
      availWidth: 1512,
      availHeight: 944,
      colorDepth: 30,
      pixelDepth: 30,
      scaleFactor: 2.0,
      isRetina: true,
    },
    scaleFactor: 2.0,
    audioSignature: {
      sampleRate: 48000,
      channelCount: 2,
      oscillatorLatencyMs: 7,
      noiseOffset: 0.00007,
      dynamicsCompressorParams: {
        threshold: -24,
        knee: 30,
        ratio: 12,
        attack: 0.003,
        release: 0.25,
      },
    },
    fontInventory: [...MAC_MODERN_FONTS],
    platformVersionRange: ['14.5', '14.6.1', '15.0', '15.2'],
    fontsClass: 'macos-modern',
    localePool: ['en-US', 'en-GB', 'de-DE', 'nl-NL', 'sv-SE', 'ja-JP'],
    coherenceConstraints: {
      mobile: false,
      platform: 'macos',
      platformArch: 'arm',
      bitness: '64',
      metalSupport: true,
    },
    uaProfile: {
      userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36',
      platformVersion: '15.0.0',
      architecture: 'arm',
      bitness: '64',
      brands: [
        { brand: 'Chromium', version: '128' },
        { brand: 'Not;A=Brand', version: '24' },
        { brand: 'Google Chrome', version: '128' },
      ],
    },
    citation: {
      source: 'Apple Developer Hardware Documentation (Mac15,3)',
      date: '2026-08',
      notes: '3nm TSMC M3 architecture with hardware dynamic caching and ray tracing support in Metal 3',
    },
    hostTellsPolicy: MACOS_HOST_TELLS_POLICY,
  },

  // 5. Apple Silicon M4 - iPad Pro / Mac mini / MacBook Pro (2024)
  {
    id: 'mac-m4-mini-2024',
    displayName: 'Mac mini / iMac (M4, 2024) / Apple M4 10-Core GPU',
    weight: 0.12,
    os: 'macos',
    chip: 'M4',
    gpu: {
      vendor: 'Apple Inc. (Apple)',
      renderer: 'ANGLE (Apple, Apple M4, OpenGL 4.1 Metal - 90.1)',
      webgpuAdapter: 'Apple M4',
      limitsClass: 'mid-range',
    },
    gpuRenderer: 'ANGLE (Apple, Apple M4, OpenGL 4.1 Metal - 90.1)',
    cpu: { coresMin: 10, coresMax: 10, arch: 'arm64' },
    ramGB: [16, 24, 32],
    screen: {
      resolutions: [{ width: 1920, height: 1080 }, { width: 2560, height: 1440 }, { width: 2048, height: 1152 }],
      dpr: 2.0,
      colorDepth: 30,
    },
    screenProfile: {
      width: 1920,
      height: 1080,
      availWidth: 1920,
      availHeight: 1055,
      colorDepth: 30,
      pixelDepth: 30,
      scaleFactor: 2.0,
      isRetina: true,
    },
    scaleFactor: 2.0,
    audioSignature: {
      sampleRate: 48000,
      channelCount: 2,
      oscillatorLatencyMs: 6,
      noiseOffset: 0.00006,
      dynamicsCompressorParams: {
        threshold: -24,
        knee: 30,
        ratio: 12,
        attack: 0.003,
        release: 0.25,
      },
    },
    fontInventory: [...MAC_MODERN_FONTS],
    platformVersionRange: ['15.0', '15.1', '15.2'],
    fontsClass: 'macos-modern',
    localePool: ['en-US', 'en-CA', 'en-GB', 'de-DE', 'fr-FR', 'ja-JP', 'ko-KR'],
    coherenceConstraints: {
      mobile: false,
      platform: 'macos',
      platformArch: 'arm',
      bitness: '64',
      metalSupport: true,
    },
    uaProfile: {
      userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36',
      platformVersion: '15.1.0',
      architecture: 'arm',
      bitness: '64',
      brands: [
        { brand: 'Chromium', version: '128' },
        { brand: 'Not;A=Brand', version: '24' },
        { brand: 'Google Chrome', version: '128' },
      ],
    },
    citation: {
      source: 'Apple Developer Hardware Documentation (Mac16,10)',
      date: '2026-08',
      notes: 'Second-generation 3nm Apple M4, 10-core CPU with upgraded neural engine and ray tracing',
    },
    hostTellsPolicy: MACOS_HOST_TELLS_POLICY,
  },

  // 6. Intel Mac - MacBook Pro 13" / 16" (2019-2020) / Intel Iris Plus Graphics
  {
    id: 'mac-intel-iris-plus-2020',
    displayName: 'MacBook Pro 13" (Intel Core i5/i7, 2020) / Intel Iris Plus Graphics 645/655',
    weight: 0.10,
    os: 'macos',
    chip: 'Intel',
    gpu: {
      vendor: 'Intel Inc. (Intel)',
      renderer: 'ANGLE (Intel, Intel Iris Plus Graphics 655, OpenGL 4.1 Metal - 88.1)',
      webgpuAdapter: 'Intel(R) Iris(TM) Plus Graphics 655',
      limitsClass: 'integrated',
    },
    gpuRenderer: 'ANGLE (Intel, Intel Iris Plus Graphics 655, OpenGL 4.1 Metal - 88.1)',
    cpu: { coresMin: 4, coresMax: 8, arch: 'x64' },
    ramGB: [8, 16],
    screen: {
      resolutions: [{ width: 1440, height: 900 }, { width: 1680, height: 1050 }],
      dpr: 2.0,
      colorDepth: 24,
    },
    screenProfile: {
      width: 1440,
      height: 900,
      availWidth: 1440,
      availHeight: 875,
      colorDepth: 24,
      pixelDepth: 24,
      scaleFactor: 2.0,
      isRetina: true,
    },
    scaleFactor: 2.0,
    audioSignature: {
      sampleRate: 44100,
      channelCount: 2,
      oscillatorLatencyMs: 9,
      noiseOffset: 0.00009,
      dynamicsCompressorParams: {
        threshold: -24,
        knee: 30,
        ratio: 12,
        attack: 0.003,
        release: 0.25,
      },
    },
    fontInventory: [...MAC_INTEL_FONTS],
    platformVersionRange: ['13.6.7', '14.4.1', '14.5', '14.6.1'],
    fontsClass: 'macos-intel',
    localePool: ['en-US', 'en-GB', 'de-DE', 'fr-FR', 'es-ES', 'it-IT'],
    coherenceConstraints: {
      mobile: false,
      platform: 'macos',
      platformArch: 'x86',
      bitness: '64',
      metalSupport: true,
    },
    uaProfile: {
      userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36',
      platformVersion: '14.5.0',
      architecture: 'x86',
      bitness: '64',
      brands: [
        { brand: 'Chromium', version: '128' },
        { brand: 'Not;A=Brand', version: '24' },
        { brand: 'Google Chrome', version: '128' },
      ],
    },
    citation: {
      source: 'Apple Developer Hardware Documentation (MacBookPro16,3 / EveryMac MBP 2020)',
      date: '2026-08',
      notes: 'Final generation 13" Intel MacBook Pro with Iris Plus Graphics and T2 security chip',
    },
    hostTellsPolicy: MACOS_HOST_TELLS_POLICY,
  },
];
