// Fetches a PINNED Node.js runtime and places it where Tauri's externalBin expects it, for the
// host the build runs on. Verifies a pinned SHA-256 before accepting the download; fails loudly on
// mismatch — the sidecar runs with the user's privileges, so an unverified binary is not an option.
//
//   Windows x64 : src-tauri/binaries/node-x86_64-pc-windows-msvc.exe   (plain node.exe)
//   macOS arm64 : src-tauri/binaries/node-aarch64-apple-darwin          (from the .tar.gz release)
//
// Usage: node scripts/vendor-node.mjs [--target <triple>]

import { existsSync, mkdirSync, createWriteStream, unlinkSync, renameSync, chmodSync, rmSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import crypto from 'node:crypto';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Pinned Node.js version and official SHA256 digest from https://nodejs.org/dist/v22.23.2/SHASUMS256.txt
// Asset: win-x64/node.exe
const NODE_VERSION = '22.23.2';

// Both digests come from https://nodejs.org/dist/v22.23.2/SHASUMS256.txt — read from that file,
// never generated by hashing whatever happened to download.
const TARGETS = {
  'node-x86_64-pc-windows-msvc.exe': {
    // Asset: win-x64/node.exe
    url: `https://nodejs.org/dist/v${NODE_VERSION}/win-x64/node.exe`,
    sha256: '0d0f5e39f9f3d9587bc19f73eab3c2c9c4903fd02d6dbf9c853dd81b3d95fad4',
    archive: null,
  },
  'node-aarch64-apple-darwin': {
    // Asset: node-v<version>-darwin-arm64.tar.gz — a tarball, so it is expanded and the binary
    // extracted rather than written straight out.
    url: `https://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}-darwin-arm64.tar.gz`,
    sha256: '61130f394c1630d211dd50aecc4353d379480f36d3ac913cd85dbba1aed585c6',
    archive: `node-v${NODE_VERSION}-darwin-arm64/bin/node`,
  },
};

/** The externalBin name Tauri expects for the host building right now. */
function defaultTargetName() {
  if (process.platform === 'darwin' && process.arch === 'arm64') return 'node-aarch64-apple-darwin';
  if (process.platform === 'win32' && process.arch === 'x64') return 'node-x86_64-pc-windows-msvc.exe';
  throw new Error(`no vendored Node target for ${process.platform}/${process.arch} — add one to TARGETS`);
}

const targetFlag = process.argv.indexOf('--target');
const TARGET_NAME = targetFlag >= 0 && process.argv[targetFlag + 1] ? process.argv[targetFlag + 1] : defaultTargetName();
const SPEC = TARGETS[TARGET_NAME];
if (!SPEC) throw new Error(`unknown target '${TARGET_NAME}'; known: ${Object.keys(TARGETS).join(', ')}`);

const URL = SPEC.url;
const EXPECTED_SHA256 = SPEC.sha256;
const TARGET_DIR = path.join(__dirname, '..', 'src-tauri', 'binaries');
const TARGET_EXE = path.join(TARGET_DIR, TARGET_NAME);

async function main() {
  if (existsSync(TARGET_EXE)) {
    // Check if existing file has expected sha256 to allow idempotency
    const existingBuffer = await import('node:fs/promises').then(fs => fs.readFile(TARGET_EXE));
    const existingHash = crypto.createHash('sha256').update(existingBuffer).digest('hex').toLowerCase();
    if (existingHash === EXPECTED_SHA256.toLowerCase()) {
      console.log(`[vendor-node] Node.js ${NODE_VERSION} (${TARGET_NAME}) already present and verified: ${TARGET_EXE}`);
      return;
    }
    console.warn(`[vendor-node] Existing binary hash mismatch (${existingHash}), re-downloading...`);
  }

  console.log(`[vendor-node] Fetching Node.js ${NODE_VERSION} runtime...`);
  console.log(`[vendor-node] GET ${URL}`);
  mkdirSync(TARGET_DIR, { recursive: true });
  const tmpExe = path.join(TARGET_DIR, `node-vendor-${NODE_VERSION}-${Date.now()}.tmp`);

  try {
    const res = await fetch(URL, { redirect: 'follow' });
    if (!res.ok || !res.body) {
      throw new Error(`Download failed with HTTP ${res.status}: ${res.statusText}`);
    }

    const hash = crypto.createHash('sha256');
    const writeStream = createWriteStream(tmpExe);

    const reader = res.body.getReader ? res.body.getReader() : null;
    if (reader) {
      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        hash.update(value);
        writeStream.write(value);
      }
      writeStream.end();
      await new Promise((resolve, reject) => {
        writeStream.on('finish', resolve);
        writeStream.on('error', reject);
      });
    } else {
      await new Promise((resolve, reject) => {
        res.body.on('data', (chunk) => {
          hash.update(chunk);
          writeStream.write(chunk);
        });
        res.body.on('error', reject);
        writeStream.on('error', reject);
        writeStream.on('finish', resolve);
        res.body.on('end', () => writeStream.end());
      });
    }

    const actualSha256 = hash.digest('hex').toLowerCase();
    if (actualSha256 !== EXPECTED_SHA256.toLowerCase()) {
      try { unlinkSync(tmpExe); } catch { /* ignore */ }
      throw new Error(`Digest mismatch for Node.js v${NODE_VERSION}: expected ${EXPECTED_SHA256}, got ${actualSha256}`);
    }

    console.log('[vendor-node] SHA-256 verified successfully.');

    if (SPEC.archive) {
      // A tarball: extract the one member that matters and place it under its externalBin name.
      const extractDir = path.join(TARGET_DIR, `node-extract-${Date.now()}`);
      mkdirSync(extractDir, { recursive: true });
      const tar = spawnSync('tar', ['-xzf', tmpExe, '-C', extractDir, SPEC.archive], { encoding: 'utf8' });
      if (tar.status !== 0) {
        throw new Error(`failed to extract ${SPEC.archive}: ${tar.stderr?.trim() || tar.status}`);
      }
      const extracted = path.join(extractDir, SPEC.archive);
      rmSync(TARGET_EXE, { force: true });
      renameSync(extracted, TARGET_EXE);
      chmodSync(TARGET_EXE, 0o755);
      rmSync(extractDir, { recursive: true, force: true });
    } else {
      renameSync(tmpExe, TARGET_EXE);
    }
    console.log(`[vendor-node] Installed vendored runtime to: ${TARGET_EXE}`);
  } catch (err) {
    try {
      if (existsSync(tmpExe)) unlinkSync(tmpExe);
    } catch { /* ignore */ }
    throw err;
  }
}

main().catch((err) => {
  console.error('[vendor-node] FAILED:', err.message);
  process.exit(1);
});
