import { Router } from 'express';
import { z } from 'zod';
import puppeteer from 'puppeteer-core';
import { getDb } from '../../db';
import * as launcher from '../../launcher/chromium';

const router = Router();

/**
 * Parse a Netscape cookies.txt line into the CDP cookie format.
 * Format (tab-separated, 7 fields):
 *   domain  includeSubdomains  path  secure  expiry  name  value
 * Lines starting with # are comments; blank lines are skipped.
 */
export function parseNetscapeLine(line: string): Record<string, unknown> | null {
  const trimmed = line.trim();
  if (!trimmed || trimmed.startsWith('#')) return null;
  const parts = trimmed.split('\t');
  if (parts.length < 7) {
    // some exporters use whitespace; fall back to multi-space split
    const ws = trimmed.split(/\s{2,}/);
    if (ws.length < 7) return null;
    parts.length = 0;
    parts.push(...ws);
  }
  const [domain, , path, secure, expiry, name, value] = parts.map((p) => p.trim());
  if (!domain || !name) return null;
  const cookie: Record<string, unknown> = {
    name,
    value,
    domain,
    path: path || '/',
    secure: secure.toUpperCase() === 'TRUE',
    httpOnly: false,
  };
  const exp = Number(expiry);
  if (Number.isFinite(exp) && exp > 0) {
    cookie.expires = exp; // CDP expects seconds since epoch
  }
  return cookie;
}

/** Parse a whole Netscape cookies.txt document. */
export function parseNetscape(text: string): Array<Record<string, unknown>> {
  const out: Array<Record<string, unknown>> = [];
  for (const line of text.split(/\r?\n/)) {
    const cookie = parseNetscapeLine(line);
    if (cookie) out.push(cookie);
  }
  return out;
}

/** Render CDP-format cookies as a Netscape cookies.txt document. */
export function toNetscape(cookies: Array<Record<string, unknown>>): string {
  const lines = ['# Netscape HTTP Cookie File', '# Generated by Antidetect Browser', ''];
  for (const c of cookies) {
    const domain = String(c.domain ?? '');
    const includeSub = domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const path = String(c.path ?? '/');
    const secure = c.secure ? 'TRUE' : 'FALSE';
    const expiresRaw = c.expires;
    const expires =
      typeof expiresRaw === 'number' && expiresRaw > 0
        ? Math.round(expiresRaw)
        : Math.round(Date.now() / 1000) + 31536000; // session-less fallback: +1 year
    const name = String(c.name ?? '');
    const value = String(c.value ?? '');
    lines.push([domain, includeSub, path, secure, String(expires), name, value].join('\t'));
  }
  return lines.join('\n') + '\n';
}

const importSchema = z.object({
  user_id: z.string(),
  cookies: z.array(z.record(z.unknown())).optional(),
  format: z.enum(['json', 'netscape']).optional(),
  text: z.string().optional(),
});

router.post('/api/v1/browser-profile/cookies/import', (req, res) => {
  const parsed = importSchema.safeParse(req.body);
  if (!parsed.success) {
    res.json({ code: -1, msg: 'invalid body', data: { errors: parsed.error.flatten() } });
    return;
  }
  const db = getDb();
  const profile = db.prepare('SELECT id FROM profiles WHERE id = ?').get(parsed.data.user_id);
  if (!profile) {
    res.json({ code: -1, msg: 'profile not found', data: {} });
    return;
  }

  // Two input shapes: structured cookies[] (json) or raw text (netscape).
  let cookies: Array<Record<string, unknown>> | undefined = parsed.data.cookies;
  if (parsed.data.format === 'netscape' || (!cookies && parsed.data.text)) {
    if (!parsed.data.text) {
      res.json({ code: -1, msg: 'text is required for netscape format', data: {} });
      return;
    }
    cookies = parseNetscape(parsed.data.text);
    if (cookies.length === 0) {
      res.json({ code: -1, msg: 'no valid cookies found in netscape text', data: {} });
      return;
    }
  }
  if (!cookies || cookies.length === 0) {
    res.json({ code: -1, msg: 'cookies[] or text is required', data: {} });
    return;
  }

  db.prepare('UPDATE profiles SET cookies_json = ?, updated_at = ? WHERE id = ?').run(
    JSON.stringify(cookies),
    Date.now(),
    parsed.data.user_id
  );
  res.json({ code: 0, msg: 'success', data: { count: cookies.length } });
});

router.get('/api/v1/browser-profile/cookies/export', async (req, res) => {
  const userId = String(req.query.user_id || '');
  const format = String(req.query.format || 'json').toLowerCase();
  const db = getDb();
  const profile = db
    .prepare('SELECT id, cookies_json FROM profiles WHERE id = ?')
    .get(userId) as { id: string; cookies_json: string | null } | undefined;
  if (!profile) {
    res.json({ code: -1, msg: 'profile not found', data: {} });
    return;
  }

  // If the profile is running, read live cookies via CDP.
  let cookies: unknown[] = [];
  let source = 'stored';
  if (launcher.isRunning(userId)) {
    const ws = launcher.getRunningWs(userId);
    if (ws) {
      try {
        const browser = await puppeteer.connect({ browserWSEndpoint: ws, defaultViewport: null });
        try {
          const targets = await browser.targets();
          const pageTarget = targets.find((t) => t.type() === 'page');
          if (pageTarget) {
            const session = await pageTarget.createCDPSession();
            const result = (await session.send('Network.getAllCookies')) as { cookies: unknown[] };
            await session.detach().catch(() => undefined);
            cookies = result.cookies;
            source = 'live';
          }
        } finally {
          browser.disconnect();
        }
      } catch {
        // fall through to stored cookies
      }
    }
  }

  if (source === 'stored' && profile.cookies_json) {
    try {
      const parsed = JSON.parse(profile.cookies_json);
      if (Array.isArray(parsed)) cookies = parsed;
    } catch {
      // ignore invalid JSON
    }
  }

  // format=netscape returns a ready-to-save cookies.txt document
  if (format === 'netscape') {
    const text = toNetscape(cookies as Array<Record<string, unknown>>);
    res.setHeader('Content-Type', 'text/plain; charset=utf-8');
    res.setHeader(
      'Content-Disposition',
      `attachment; filename="cookies-${userId}.txt"`
    );
    res.send(text);
    return;
  }

  res.json({ code: 0, msg: 'success', data: { cookies, source } });
});

export default router;
