// Auto-generated by scripts/sync-license-key.mjs — DO NOT EDIT MANUALLY.
// Pinned Ed25519 public key for offline license validation.
// The matching PRIVATE KEY is NEVER committed.
// Run 'node scripts/sync-license-key.mjs' after rotating resources/license-public-key.pem.

export const LICENSE_PUBLIC_KEY_PEM = "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEApGc8UHnevzlWqxvgFda8OAir7sggngcs62nD0+0yp1I=\n-----END PUBLIC KEY-----\n";
