import { describe, it, expect } from 'vitest';
import * as fs from 'fs';
import * as path from 'path';

describe('Tauri Packaging Targets and Portable Pipeline (release 0.5.0)', () => {
  const root = path.resolve(__dirname, '../..');
  const tauriConfPath = path.join(root, 'src-tauri', 'tauri.conf.json');
  const pkgJsonPath = path.join(root, 'package.json');
  const buildPortableScriptPath = path.join(root, 'scripts', 'build-portable.mjs');

  const tauriConf = JSON.parse(fs.readFileSync(tauriConfPath, 'utf8'));
  const pkg = JSON.parse(fs.readFileSync(pkgJsonPath, 'utf8'));
  const buildPortableScript = fs.readFileSync(buildPortableScriptPath, 'utf8');

  it('tauri.conf.json bundle targets include nsis installer artefact', () => {
    const targets = tauriConf.bundle?.targets;
    // Tauri bundle targets should either include 'nsis' or be configured for windows installer
    if (Array.isArray(targets)) {
      expect(targets).toContain('nsis');
    } else {
      expect(tauriConf.bundle?.windows?.nsis).toBeDefined();
    }
  });

  it('scripts/build-portable.mjs creates single-file portable Windows artefact without installing', () => {
    expect(fs.existsSync(buildPortableScriptPath)).toBe(true);
    // Script derives version from tauri.conf.json
    expect(buildPortableScript).toMatch(/tauri\.conf\.json/);
    // Script names portable artifact NullTrace-<version>-portable-win-x64.exe
    expect(buildPortableScript).toMatch(/NullTrace-.*-portable-win-x64\.exe/);
    // Wraps shell in self-extracting portable launcher (e.g. makensis portable.nsi)
    expect(buildPortableScript).toMatch(/makensis|portable\.nsi/i);
  });

  it('installer and portable artefacts have distinct, self-describing names', () => {
    // Installer artifact generated by Tauri NSIS vs portable generated by build-portable.mjs
    const portablePattern = /NullTrace-(?:.*)-portable-win-x64\.exe/;
    expect('NullTrace-0.5.0-portable-win-x64.exe').toMatch(portablePattern);
    // NSIS installer is distinct (setup installer, not portable)
    const installerName = 'NullTrace_0.5.0_x64-setup.exe';
    expect(installerName).not.toMatch(portablePattern);
    expect(installerName).toContain('setup');
  });

  it('browser kernel is NOT bundled into the application resources (fetched at runtime)', () => {
    const resources = tauriConf.bundle?.resources;
    if (resources) {
      const resourceList = Array.isArray(resources) ? resources : Object.keys(resources);
      for (const res of resourceList) {
        expect(res).not.toMatch(/fingerprint-chromium/i);
        expect(res).not.toMatch(/kernel/i);
      }
    }
  });

  it('package.json scripts define tauri:build to produce shell artefacts', () => {
    expect(pkg.scripts?.['tauri:build']).toBeDefined();
    expect(pkg.scripts['tauri:build']).toMatch(/tauri build/);
  });

  it('tauri externalBin includes node-service binary', () => {
    const externalBin = tauriConf.bundle?.externalBin;
    expect(Array.isArray(externalBin)).toBe(true);
    expect(externalBin).toContain('binaries/node');
  });

  // Three artefacts reach the operator: the shell, Tauri's NSIS setup (and the uninstaller
  // it writes), and our own portable launcher. Only the shell had the brand mark — the other
  // two shipped the stock NSIS `modern-install.ico`, because nothing wired the icon in.
  // A test rather than a build-time check: the failure is invisible until someone looks at
  // the .exe in Explorer, which is exactly how it survived a release.
  it('every Windows artefact is wired to the brand icon', () => {
    const iconPath = path.join(root, 'src-tauri', 'icons', 'icon.ico');
    expect(fs.existsSync(iconPath)).toBe(true);

    // NSIS setup + its uninstaller: without these, Tauri compiles its own default in.
    expect(tauriConf.bundle?.windows?.nsis?.installerIcon).toBe('icons/icon.ico');
    expect(tauriConf.bundle?.windows?.nsis?.uninstallerIcon).toBe('icons/icon.ico');

    // Portable launcher: our template compiles it, so the icon has to arrive via a define.
    const template = fs.readFileSync(path.join(root, 'src-tauri', 'windows', 'portable.nsi'), 'utf8');
    expect(template).toMatch(/^\s*Icon\s+"\$\{ICONPATH\}"/m);

    // and the build script must actually substitute that placeholder.
    expect(buildPortableScript).toMatch(/icon_path/);
    expect(buildPortableScript).toMatch(/'icons',\s*'icon\.ico'/);
  });
});
